import './globals.css'
import Link from 'next/link'
// import { useEffect, useState } from 'react'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default async function RootLayout({children}) {
  // const [topics, setTopics] = useState([]);

  // useEffect(() => {
    // fetch('http://localhost:9999/topics')
    //   .then(resp => resp.json())
    //   .then(result=>{
    //     setTopics(result);
    //   });
  // }, []);
  const resp = await fetch('http://localhost:9999/topics');
  const topics = await resp.json();

  return (
    <html lang="ko">
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {
            topics.map((topic)=>{
              return <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>
                  {topic.title}
                </Link>
              </li>
            })
          }
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="Delete" /></li>
        </ul>
      </body>
    </html>
  )
}
